Models/EF/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CosmeticsStore.Models.EF
{
    [Table("tb_Contact")]
    public class Contact : CommonAbstract
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(50, ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Name { get; set; }
        [StringLength(50, ErrorMessage = "Không được vượt quá 150 ký tự")]
        public string Email { get; set; }
        public string Website { get; set; }
        public string Messsage { get; set; }
        public bool IsRead {get; set; }
    }
}

Controllers/ContactController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class ContactController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Contact
        public ActionResult Index()
        {
            var items = db.Branchs.OrderBy(x => x.Id).ToList();
            return View(items);
        }
    }
}

Controllers/HomeController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using Dapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;

namespace CosmeticsStore.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Index()
        {
            string userId = User.Identity.GetUserId();
            ViewBag.UserId = userId;
            return View();
        }

        public ActionResult Partial_Subcrise()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Subscribe(Subscribe req)
        {
            if (ModelState.IsValid)
            {
                db.Subscribes.Add(new Subscribe { Email = req.Email, CreatedDate = DateTime.Now });
                db.SaveChanges();
                return Json(new { Success = true });
            }
            return View("Partial_Subcrise", req);
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        public ActionResult Refesh()
        {
            var item = new ThongKeModel();
            ViewBag.Visitors_online = HttpContext.Application["visitors_online"];
            var hn = HttpContext.Application["HomNay"];
            item.HomNay = HttpContext.Application["HomNay"].ToString();
            item.HomQua = HttpContext.Application["HomQua"].ToString();
            item.TuanNay = HttpContext.Application["TuanNay"].ToString();
            item.TuanTruoc = HttpContext.Application["TuanTruoc"].ToString();
            item.ThangNay = HttpContext.Application["ThangNay"].ToString();
            item.ThangTruoc = HttpContext.Application["ThangTruoc"].ToString();
            item.TatCa = HttpContext.Application["TatCa"].ToString();
            return PartialView(item);
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [HttpPost]
        public ActionResult BookAppointment(string selectedDate, string selectedHour, string name, string phone, string email, string serviceId, string branchId)
        {
            // Chuyển đổi giá trị hour thành kiểu DateTime
            DateTime bookingTime = DateTime.ParseExact(selectedDate + " " + selectedHour, "MM/dd/yyyy HH:mm", CultureInfo.InvariantCulture);
            List<Bookings> userBookings = db.Bookings.Where(b => b.Phone == phone).ToList();
            bool isBooked = userBookings.Any(b => b.Date == bookingTime.ToString());

            List<Bookings> bookedHours = GetBookedHours(phone); // Lấy danh sách các giờ đã đặt
            bool isSlotAvailable = IsBookingSlotAvailable(bookingTime, bookedHours);

            if (!isSlotAvailable)
            {
                return Json(new { success = false, message = "Khoảng thời gian đã được đặt." });
                Debug.WriteLine("isBooked " + isBooked);
            }
            Debug.WriteLine("isBooked " + isBooked);
            if (isBooked)
            {
                return Json(new { success = false, message = "Bạn đã có lịch hẹn vào thời gian này." });
            }
            else
            {
                string code = phone + "_" + bookingTime.ToString("yyyyMMddHHmm");
                // Lưu thông tin booking vào database
                Bookings booking = new Bookings
                {
                    Code = code,
                    CustomerName = HttpUtility.UrlDecode(name, Encoding.UTF8),
                    Phone = phone,
                    Date = bookingTime.ToString(),
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    Status = "Chờ xác nhận",
                    serviceId = serviceId,
                };
                // Thêm đối tượng Booking vào database
                db.Bookings.Add(booking);
                db.SaveChanges();
                var service = db.Services.FirstOrDefault(s => s.Id.ToString() == serviceId);
                if (service != null)
                {
                    var bookingDetails = new BookingDetails
                    {
                        ServiceId = service.Id,
                        BookingId = code,
                        Price = service.Price,
                        ServiceDetail = service.Detail,
                        ServiceName = service.Title,
                        BranchId = (int)Convert.ToInt32(branchId)
                };

                    db.BookingDetails.Add(bookingDetails);
                    db.SaveChanges();
                }
                return Json(new { success = true });
            }
            
        }

        public bool IsBookingSlotAvailable(DateTime selectedHour, List<Bookings> bookedHours)
        {
            DateTime endHour = selectedHour.AddHours(1);

            foreach (var bookedHour in bookedHours)
            {
                DateTime bookingTime = DateTime.Parse(bookedHour.Date);

                if ((selectedHour >= bookingTime && selectedHour < bookingTime.AddHours(1)) ||
                    (bookingTime >= selectedHour && bookingTime < endHour))
                {
                    return false;
                }
            }

            return true;
        }


        public List<Bookings> GetBookedHours(string phone)
        {
            List<Bookings> bookedHours = db.Bookings.Where(p => p.Phone == phone).ToList();
            return bookedHours;
        }





    }
}

Controllers/MenuController.cs
using CosmeticsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MenuTop()
        {
            var items = db.Categories.OrderBy(x => x.Position).ToList();
            return PartialView("MenuTop", items);
        }
        public ActionResult MenuProductCategory()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuProductCategory", items);
        }
        public ActionResult MenuLeft(int? id)
        {
            if(id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.ProductCategories.ToList();
            return PartialView("MenuLeft", items);
        }
        public ActionResult MenuArrivals()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuArrivals", items);
        }
    }
}

Controllers/NewsController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: News
        public ActionResult Index(int? page)
        {
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable< News > items = db.News.OrderByDescending(x => x.CreatedDate).ToList();
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Detail(int id)
        {
            var item = db.News.Find(id);
            return View(item);
        }
        public ActionResult Partial_News_Home() 
        {   
            var item = db.News.Take(3).ToList();
            return PartialView(item); 
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
<!-- Slider -->
<div style="background-color:bisque; padding-top:130px;" class="deal_ofthe_week">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="deal_ofthe_week_img">
                    <img style="width: 90%; height: auto" src="~/Content/assets/images/image-removebg-preview.png" />
                </div>
            </div>
            <div class="col-lg-6 text-right deal_ofthe_week_col">
                <div class="deal_ofthe_week_content d-flex flex-column align-items-center float-right">
                    <div class="section_title">
                        <h2>Khuyến mãi trong tuần</h2>
                    </div>
                    <ul class="timer">
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="day" class="timer_num">03</div>
                            <div class="timer_unit">Ngày</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="hour" class="timer_num">15</div>
                            <div class="timer_unit">Giờ</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="minute" class="timer_num">45</div>
                            <div class="timer_unit">Phút</div>
                        </li>
                        <li class="d-inline-flex flex-column justify-content-center align-items-center">
                            <div id="second" class="timer_num">23</div>
                            <div class="timer_unit">Giây</div>
                        </li>
                    </ul>
                    <div class="row">
                        <div class="col-6">
                            <div class="red_button deal_ofthe_week_button"><a style="color:#fff" href="/dat-lich"><span class="glyphicon glyphicon-calendar"></span><span>  Đặt Lịch</span></a></div>
                        </div>
                        <div class="col-6">
                            <div class="red_button deal_ofthe_week_button"><a style="color:#fff" href="/san-pham"><span class="fa fa-shopping-cart"></span><span>  Mua Sắm</span></a></div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner -->
@Html.Action("MenuProductCategory", "Menu")


<!-- Best Sellers -->

@Html.Action("Partial_ProductSales", "Products")


<!-- Benefit -->
@Html.Action("Partial_News_Home", "News")

<div class="benefit">
    <div class="container">
        <div class="row benefit_row">
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-truck" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Miễn phí vận chuyển</h6>
                        <p>Nhấc máy lên và gọi ngay</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-money" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Thanh toán nhận hàng</h6>
                        <p>Dịch vụ thanh toán 24/24</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-undo" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>45 ngày hoàn trả</h6>
                        <p>Uy tín chất lượng</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i class="fa fa-clock-o" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Mở cửa cả tuần</h6>
                        <p>8AM - 9PM</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Blogs -->

Views/Home/Partial_Search.cshtml
@model string

@{
    ViewData["Title"] = "Full Text Search";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


<div class="main">

    <!-- Actual search box -->
    <div class="form-group has-search">
        <span class="fa fa-search form-control-feedback"></span>
        <input type="text" class="form-control" placeholder="Search" id="searchQuery" name="searchQuery">
    </div>
    <div class="searchResult" id="searchResults"></div>
</div>


<style>
    /* Styles for wrapping the search box */

    .main {
        width: 50%;
        margin: 50px auto;
    }

    /* Bootstrap 4 text input with search icon */

    .has-search .form-control {
        padding-left: 2.375rem;
    }

    .has-search .form-control-feedback {
        position: absolute;
        z-index: 2;
        display: block;
        width: 2.375rem;
        height: 2.375rem;
        line-height: 2.375rem;
        text-align: center;
        pointer-events: none;
        color: black;
    }

    .product{
        height: 100px;
    }
    .image {
        width: 60px;
        height: 50px;
    }
</style>

@section Scripts {
    <script>
        const searchQuery = document.getElementById("searchQuery");
        const searchResults = document.getElementById("searchResults");

        searchQuery.addEventListener("input", () => {
            const query = searchQuery.value;
            const searchResultUrl = '@Url.Action("SearchProducts", "Home")';

            if (query.length > 0) {
                fetch(`/Home/SearchProducts?searchQuery=${query}`)
                    .then(response => response.json())
                    .then(result => {
                        let html = '';
                        if (result != null && result.length > 0) {
                            result.forEach(product => {
                                html += `
                                    <div class="product">
                                        <h3>${product.Title}</h3>
                                        <div>
                                        <p>${product.Description}</p>
                                        <img src="${product.Image}" class="image"/>
                                        </div>
                                    </div>
                                `;
                            });
                        } else {
                            html = '<p>Không tìm thấy sản phẩm nào.</p>';
                        }
                        searchResults.innerHTML = html;
                    }

                    )
                    .catch(error => console.error(error));
            } else {
                searchResults.innerHTML = "";
            }
        });
    </script>
}

Views/Home/Partial_Subcrise.cshtml
@model CosmeticsStore.Models.EF.Subscribe
<div class="newsletter">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="newsletter_text d-flex flex-column justify-content-center align-items-lg-start align-items-md-center text-center">
                    <h4>Đăng ký</h4>
                    <p>Đăng ký để mua đơn hàng đầu tiên được giảm giá 20%</p>
                </div>
            </div>
            <div class="col-lg-6">
                @using (Ajax.BeginForm("Subscribe", "Home", new AjaxOptions
                {
                    OnBegin = "OnBeginSub",
                    OnSuccess = "OnSuccessSub",
                    OnFailure = "OnFailureSub"
                }))
                {
                    @Html.AntiForgeryToken()
                    <script>
                        function OnBeginSub(rs) {

                        }
                        function OnSuccessSub(rs) {
                            if (rs.Success) {
                                alert("Bạn đã đăng ký thành công");
                            }
                        }
                        function OnFailureSub(rs) {
                            if (rs.Success) {
                                alert("aaa");
                            }
                        }
                    </script>
                    <div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-lg-end justify-content-center">
                        @*@Html.TextBoxFor(x => x.Email, new {})*@
                        <input id="newsletter_email" name="Email" type="email" placeholder="Your email" required="required" data-error="Valid email is required.">
                        <button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">subscribe</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

Views/Home/Refesh.cshtml
@model CosmeticsStore.Models.ThongKeModel
@if (Model != null)
{
    <div class="thongke">
        <table class="table">
            <tr>
                <td>Hôm Nay</td>
                <td>@Model.HomNay</td>
            </tr>
            <tr>
                <td>Hôm Qua</td>
                <td>@Model.HomQua</td>
            </tr>
            <tr>
                <td>Tuần Này</td>
                <td>@Model.TuanNay</td>
            </tr>
            <tr>
                <td>Tuần Trước</td>
                <td>@Model.TuanTruoc</td>
            </tr>
            <tr>
                <td>Tháng Này</td>
                <td>@Model.ThangNay</td>
            </tr>
            <tr>
                <td>Tháng Trước</td>
                <td>@Model.ThangTruoc</td>
            </tr>
            <tr>
                <td>Số Người Online</td>
                <td>@ViewBag.Visitors_online</td>
            </tr>

        </table>

    </div>
}