Models/EF/Service.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CosmeticsStore.Models.EF
{
    [Table("tb_Service")]
    public class Service : CommonAbstract
    {
        public Service()
        {
            this.ServiceImage = new HashSet<ServiceImages>();
            this.BookingDetails = new HashSet<BookingDetails>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Title { get; set; }
        public string Alias { get; set; }
        [StringLength(50)]
        public string ServiceCode { get; set; }
        public string Description { get; set; }
        [AllowHtml]
        public string Detail { get; set; }
        public string Image { get; set; }
        public decimal Price { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public bool IsActive { get; set; }
        public int ServiceCategoryId { get; set; }
        public virtual ICollection<ServiceImages> ServiceImage { get; set; }
        public virtual ICollection<BookingDetails> BookingDetails { get; set; }
    }
}

Controllers/MenuController.cs
using CosmeticsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MenuTop()
        {
            var items = db.Categories.OrderBy(x => x.Position).ToList();
            return PartialView("MenuTop", items);
        }
        public ActionResult MenuProductCategory()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuProductCategory", items);
        }
        public ActionResult MenuLeft(int? id)
        {
            if(id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.ProductCategories.ToList();
            return PartialView("MenuLeft", items);
        }
        public ActionResult MenuArrivals()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuArrivals", items);
        }
    }
}

Controllers/ServicesController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using Geocoding;
using Geocoding.Google;
using Hangfire;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Linq;
using PagedList;
using System;
using System.Collections.Generic;
using System.Device.Location;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Location = CosmeticsStore.Models.Location;

namespace CosmeticsStore.Controllers
{
    public class ServicesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Branchs nearestBranch = new Branchs();
        double longtitude = 0;
        double latitude = 0;
        // GET: Services
        public ActionResult Index(string Searchtext, int? page)
        {
            IEnumerable<Models.EF.Service> items = db.Services.OrderBy(x => x.Title);
            var pageSize = 12;
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;


            string userId = User.Identity.GetUserId();
            var user = db.Users.FirstOrDefault(u => u.Id == userId);
            // Kiểm tra trạng thái cấm đặt lịch của khách hàng
           if(user != null)
            {
                if (user.IsBanned)
                {
                    // Tính số ngày bị cấm
                    int bannedDays = user.BanExpirationDate.Value.Subtract(DateTime.Now).Days;

                    // Hiển thị thông báo cảnh báo
                    string message = $"Bạn đã bị cấm đặt lịch trong {bannedDays} ngày.";
                    ViewBag.Script = message;
                }
            }
            BackgroundJob.Schedule(() => UpdateBookingStatus(), TimeSpan.FromMinutes(1));
            BackgroundJob.Schedule(() => UpdateBookingStatusForBan(), TimeSpan.FromMinutes(1));

            // Định cấu hình công việc lập lịch
            RecurringJob.AddOrUpdate(() => CheckCustomerBookingStatus(), Cron.Daily);
            return View(items);
        }

        public ActionResult SortByName(string Searchtext)
        {
            IEnumerable<Models.EF.Service> items = db.Services.OrderBy(x => x.Title).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult SortByPrice(string Searchtext)
        {
            IEnumerable<Models.EF.Service> items = db.Services.OrderBy(x => x.Price).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult SortByPriceGiam(string Searchtext)
        {
            IEnumerable<Models.EF.Service> items = db.Services.OrderByDescending(x => x.Price).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult SortByNameZA(string Searchtext)
        {
            IEnumerable<Models.EF.Service> items = db.Services.OrderByDescending(x => x.Title).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult Detail(string alias, int id)
        {
            var item = db.Services.Find(id);
            if (item != null)
            {
                db.Services.Attach(item);
                /*item.ViewCount = item.ViewCount + 1;
                db.Entry(item).Property(x => x.ViewCount).IsModified = true;
                db.SaveChanges();*/
            }

            return View(item);
        }
        public List<HourModel> CurentDay(DateTime currentDate)
        {
            var startHour = 8;
            var endHour = 18;
            var hoursOfDay = new List<HourModel>();
            for (int i = 0; i < 96; i++) // 96 slot = 1 ngày (24 giờ x 4 slot/giờ)
            {
                var currentHour = currentDate.AddMinutes(i * 15);

                if (currentHour.Hour >= startHour && currentHour.Hour < endHour)
                {
                    var hourModel = new HourModel
                    {

Views/Services/ConfirmBooking.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Xác nhận đặt lịch</title>
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_styles.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_responsive.css">

</head>
<body>
    <div class="container product_section_container">
        <div class="row">
            <div class="col product_section clearfix">

                <!-- Breadcrumbs -->

                <div class="breadcrumbs d-flex flex-row align-items-center">
                    <ul>
                        <li><a href="san-pham">Đặt lịch</a></li>
                        <li class="active"><a href="/"><i class="fa fa-angle-right" aria-hidden="true"></i>@ViewBag.CateName</a></li>
                    </ul>
                </div>

                <!-- Sidebar -->

                <div class="sidebar">
                    <!--<div class="sidebar_section">
                        <div class="sidebar_title">
                            <h5>Danh Mục Sản Phẩm</h5>
                        </div>-->
                    @*@Html.Action("MenuLeft", "Menu", new { id = ViewBag.CateId })*@
                    <!--</div>-->
                    <!-- Price Range Filtering -->
                    <div class="sidebar_section">

                        @Html.Action("Refesh", "Home")
                    </div>
                </div>

                <!-- Main Content -->

                <div class="main_content">

                    <div class="products_iso" style="text-align: center; justify-content: flex-start">
                        <img src="https://i.pinimg.com/originals/74/2f/7e/742f7ea29cbfd7fd3f4848f17e621070.gif" style="background-color: white" alt="Success" width="300" height="200">
                        <h3 style="text-align: center">Cảm ơn bạn đã đặt lịch tại phòng khám chúng tôi.</h3>
                        <h3 style="text-align: center; color: #808080; font-weight: bold">Bạn sẽ nhận được cuộc gọi xác nhận trong vòng 60 phút.</h3>
                        <p style="text-align: center; font-size: 20px">Thông tin đặt lịch của bạn như sau:</p>
                        <p id="booking-info" style="text-align: center"></p>
                        <button onclick="goBack()" style="font-size: 20px; padding: 10px 20px; background-color: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer;">Trở lại</button>
                        <button onclick="history()" style="font-size: 20px; padding: 10px 20px; background-color: #4CAF50; color: white; border: none; border-radius: 5px; cursor: pointer;">Lịch sử</button>
                    </div>
                </div>
            </div>
            </div>
        </div>
    
    <script>
                // Lấy thông tin đặt lịch từ URL query string
                var urlParams = new URLSearchParams(window.location.search);
                var name = urlParams.get('name');
                var email = urlParams.get('email');
                var phone = urlParams.get('phone');
                var date = urlParams.get('date');
                var time = urlParams.get('time');

                // Hiển thị thông tin đặt lịch trên trang
                document.getElementById("booking-info").innerHTML = "Họ và tên: " + name + "<br>Email: " + email + "<br>Số điện thoại: " + phone + "<br>Ngày hẹn: " + date + "<br>Giờ hẹn: " + time;

                // Chuyển về trang đặt lịch nếu người dùng muốn đặt lịch thêm
                function goBack() {
                    window.history.back();
                }
                function history() {
                    var confirmUrl = '@Url.Action("History", "Services")';
                    window.location.replace(confirmUrl);
                }
    </script>
</body>
</html>

Views/Services/History.cshtml
<!-- Import thư viện Bootstrap -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_responsive.css">
<div class="container product_section_container">
    <div class="row">
        <div class="col product_section clearfix">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">
                <ul>
                    <li><a href="san-pham">Đặt lịch</a></li>
                    <li class="active"><a href="/"><i class="fa fa-angle-right" aria-hidden="true"></i>@ViewBag.CateName</a></li>
                </ul>
            </div>

            <!-- Sidebar -->

            <div class="sidebar">
                <!--<div class="sidebar_section">
                    <div class="sidebar_title">
                        <h5>Danh Mục Sản Phẩm</h5>
                    </div>-->
                @*@Html.Action("MenuLeft", "Menu", new { id = ViewBag.CateId })*@
                <!--</div>-->
                <!-- Price Range Filtering -->
                <div class="sidebar_section">

                    @Html.Action("Refesh", "Home")
                </div>
            </div>

            <!-- Main Content -->

            <div class="main_content">

                <div class="products_iso">
                    <h2 style="text-align: center">Lịch sử đặt lịch</h2>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Dịch vụ</th>
                                <th>Ngày đặt</th>
                                <th>Trạng thái</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.History)
                            {
                                <tr>
                                    <td>@item.ServiceName</td>
                                    <td>@item.Date.ToString("dd/MM/yyyy")</td>
                                    <td><span @if (item.Status == "Chờ xác nhận") { <text> class="pending" </text> } @if (item.Status == "Đã hủy") { <text> class="cancel" </text> } @if (item.Status == "Hoàn thành") { <text> class="done" </text> }>@item.Status</span></td>
                                    <td><button id="btnCancel" data-id="@item.Code" class="btn btn-lg btn-danger @if (item.Status == "Đã hủy" || item.Status == "Hoàn thành" || item.Status == "Đã xác nhận") { <text>disabled</text> }">Hủy</button></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .pending {
        border-radius: 5px;
        background-color: yellow;
    }

    .cancel {
        color: white;
        border-radius: 5px;
        background-color: #de0b40;
    }

    .done {
        color: white;
        border-radius: 5px;
        background-color: #37d45e;
    }
</style>

<script>
    function cancelAppointment(code) {
        swal({
            title: 'Thông báo',
            text: 'Bạn có chắc muốn hủy đặt lịch này không?',
            icon: 'warning',
            buttons: true,
            dangerMode: true
        }).then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CancelAppointment", "Services")',
                    data: { code: code },
                    success: function (result) {
                        if (result.success) {
                            swal({
                                title: 'Thông báo',
                                text: result.message,
                                icon: 'success',
                                button: "Đóng",
                            }).then((value) => {
                                location.reload();
                            });
                        } else {
                            swal({
                                title: 'Thông báo',
                                text: result.message,
                                icon: 'warning',
                                button: 'Đóng'
                            });
                        }
                    },
                    error: function () {
                        swal({
                            title: 'Thông báo',
                            text: 'Có lỗi xảy ra khi hủy đặt lịch. Vui lòng thử lại sau.',
                            icon: 'error',
                            button: 'Đóng'
                        });
                    }
                });
            }
        })
    }
    $(function () {
        $('body').on('click', '.cancel-appointment', function () {
            var id = $(this).data('id');
            cancelAppointment(id);
        });
    });

    $(function () {
        $('body').on('click', '#btnCancel', function () {
            var id = $(this).closest('tr').find('.cancel-appointment').data('id');
            var code = $(this).data('id');
            cancelAppointment(code);
        });
    });

    function updateAppointmentStatus(id, status) {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UpdateAppointmentStatus", "Services")',
            data: { id: id, status: status },
            success: function (result) {
            if (result.success) {
                alert(result.message);
                swal({
                    title: 'Thông báo',
                    text: result.message,
                    icon: 'success',
                    button: 'Đóng'
                });
            } else {
                swal({
                    title: 'Thông báo',
                    text: result.message,
                    icon: 'error',
                    button: 'Đóng'
                });
                }
            },
            error: function () {
                swal({
                    title: 'Thông báo',
                    text: 'Có lỗi xảy ra khi cập nhật trạng thái đặt lịch. Vui lòng thử lại sau.',
                    icon: 'error',
                    button: 'Đóng'
                });
            }
            });
            }
</script>
@section scripts{
    <script src="~/Content/assets/js/categories_custom.js"></script>
}

Views/Services/SortByName.cshtml
@model IEnumerable<CosmeticsStore.Models.EF.Service>
@{
    ViewBag.Title = "Danh sách Dịch Vụ";
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_responsive.css">

<div class="container product_section_container">
    <div class="row">
        <div class="col product_section clearfix">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">
                <ul>
                    <li><a href="dat-lich">Đặt Lịch</a></li>
                    <li class="active"><a href="/"><i class="fa fa-angle-right" aria-hidden="true"></i>@ViewBag.CateName</a></li>
                </ul>
            </div>

            <!-- Sidebar -->

            <div class="sidebar">
                <!--<div class="sidebar_section">
                    <div class="sidebar_title">
                        <h5>Danh Mục Sản Phẩm</h5>
                    </div>-->
                    @*@Html.Action("MenuLeft", "Menu", new { id = ViewBag.CateId })*@
                <!--</div>-->

                <!-- Price Range Filtering -->
                <div class="sidebar_section">
                    @*<div class="sidebar_title">
                        <h5>Lọc theo Giá</h5>
                    </div>
                    <p>
                        <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
                        <input type="hidden" id="FromAmount" />
                        <input type="hidden" id="ToAmount" />
                    </p>
                    <div id="slider-range"></div>
                    <div class="filter_button"><span>Lọc</span></div>

                    <hr />*@
                    @Html.Action("Refesh", "Home")
                </div>
            </div>

            <!-- Main Content -->

            <div class="main_content">

                <!-- Products -->

                <div class="products_iso">
                    <div class="row">
                        <div class="col-10">

                            <!-- Product Sorting -->

                            <div class="product_sorting_container product_sorting_container_top">
                                <ul class="product_sorting">
                                    <li>
                                        <span class="type_sorting_text">Sắp xếp</span>
                                        <i class="fa fa-angle-down"></i>
                                        <ul class="sorting_type">
                                            <li><a style="color: #fe4c50" href="~/Services/index">Mặc Định</a></li>
                                            <li><a style="color: #fe4c50" href="~/Services/SortByName">A -> Z</a></li>
                                            <li><a style="color: #fe4c50" href="~/Services/SortByNameZA">Z -> A</a></li>
                                            <li><a style="color: #fe4c50" href="~/Services/SortByPrice">Giá Tăng Dần</a></li>
                                            <li><a style="color: #fe4c50" href="~/Services/SortByPriceGiam">Giá Giảm Dần</a></li>
                                        </ul>
                                    </li>
                                    @*<li>
                                            <span>Show</span>
                                            <span class="num_sorting_text">6</span>
                                            <i class="fa fa-angle-down"></i>
                                            <ul class="sorting_num">
                                                <li class="num_sorting_btn"><span>6</span></li>
                                                <li class="num_sorting_btn"><span>12</span></li>
                                                <li class="num_sorting_btn"><span>24</span></li>
                                            </ul>
                                        </li>*@
                                </ul>

                            </div>

                        </div>
                        <div class="col-2">
                            <form>
                                @using (Html.BeginForm("index", "Services", FormMethod.Get, new { }))
                                {
                                    <div class="search-box">
                                        <input id="Searchtext" name="Searchtext" type="text" placeholder="Tên dịch vụ">
                                        <button type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                    @*<div class="input-group">
                                            <input id="Searchtext" name="Searchtext" type="text" class="form-control" placeholder="Tên sản phẩm">
                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-lg btn-outline-danger">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                        </div>*@
                                }

                            </form>
                        </div>

                    </div>

                    <!-- Product Grid -->

                    <div class="product-grid">

                        <!-- Product 1 -->
                        @if (Model != null && Model.Any())
                        {
                            foreach (var item in Model)
                            {
                                <!-- Product 1 -->
                                var strImge = "";
                                var img = item.ServiceImage.FirstOrDefault(x => x.IsDefault);
                                if (img != null)
                                {
                                    strImge = img.Image;
                                }
                                <div class="product-item">
                                    <div class="product discount product_filter">
                                        <div class="product_image">
                                            <img src="@strImge" alt="@item.Title">
                                        </div>
                                        <div class="favorite favorite_left"></div>

                                        <div class="product_info">
                                            <h6 class="product_name"><a href="/chi-tiet-dich-vu/@item.Alias-p@(item.Id)">@item.Title</a></h6>
                                            <div class="product_price">@CosmeticsStore.Common.Common.FormatNumber(item.Price, 0)</div>
                                        </div>
                                    </div>
                                    <div class="red_button dat_lich_button"><a href="#" class="btnAddToCart" data-id="@item.Id">Đặt Lịch</a></div>

                                </div>
                            }
                        }

                    </div>
                    <!-- Product Sorting -->
                    @*<div class="product_sorting_container product_sorting_container_bottom clearfix">
                            <ul class="product_sorting">
                                <li>
                                    <span>Show:</span>
                                    <span class="num_sorting_text">04</span>
                                    <i class="fa fa-angle-down"></i>
                                    <ul class="sorting_num">
                                        <li class="num_sorting_btn"><span>01</span></li>
                                        <li class="num_sorting_btn"><span>02</span></li>
                                        <li class="num_sorting_btn"><span>03</span></li>
                                        <li class="num_sorting_btn"><span>04</span></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>*@

                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/assets/js/categories_custom.js"></script>
}