Models/EF/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CosmeticsStore.Models.EF
{
    [Table("tb_ProductCategory")]
    public class ProductCategory:CommonAbstract
    {
        public ProductCategory() 
        {
            this.Products = new HashSet<Product>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        public string Alias { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

Models/EF/Products.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CosmeticsStore.Models.EF
{
    [Table("tb_Product")]
    public class Product : CommonAbstract
    {
        public Product()
        {
            this.ProductImage = new HashSet<ProductImage>();
            this.OrderDetail = new HashSet<OrderDetail>();
        }
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [StringLength(250)]
        public string Title { get; set; }
        public string Alias { get; set; }
        [StringLength(50)]
        public string ProductCode { get; set; }
        public string Description { get; set; }
        [AllowHtml]
        public string Detail { get; set; }
        public string Image { get; set; }
        public decimal OriginalPrice { get; set;}
        public decimal Price { get; set; }
        public decimal PriceScale { get; set; }
        public int Quantity { get; set; }
        public int ViewCount { get; set; }
        public bool IsHome { get; set; }
        public bool IsSale { get; set; }
        public bool IsFeature { get; set; }
        public bool IsHot { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeywords { get; set; }
        public bool IsActive { get; set; }
        public int ProductCategoryId { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public float StarRating { get; set; }
    }
}

Controllers/MenuController.cs
using CosmeticsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MenuTop()
        {
            var items = db.Categories.OrderBy(x => x.Position).ToList();
            return PartialView("MenuTop", items);
        }
        public ActionResult MenuProductCategory()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuProductCategory", items);
        }
        public ActionResult MenuLeft(int? id)
        {
            if(id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.ProductCategories.ToList();
            return PartialView("MenuLeft", items);
        }
        public ActionResult MenuArrivals()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuArrivals", items);
        }
    }
}

Controllers/PostsController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsStore.Controllers
{
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Posts
        public ActionResult Index(int? page)
        {
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Posts> items = db.Posts.OrderByDescending(x => x.CreatedDate).ToList();
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Detail(int id)
        {
            var item = db.Posts.Find(id);
            return View(item);
        }
        public ActionResult Partial_Posts_Home()
        {
            var item = db.Posts.Take(3).ToList();
            return PartialView(item);
        }
    }
}

Controllers/ProductsController.cs
using CosmeticsStore.Models;
using CosmeticsStore.Models.EF;
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using PagedList;


namespace CosmeticsStore.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Products
        public ActionResult Index(string Searchtext, int? page)
        {
            IEnumerable<Product> items = db.Products.OrderBy(x => x.Title);
            var pageSize = 12;
            if (page == null)
            {
                page = 1;
            }
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult SortByName(string Searchtext)
        {
            IEnumerable<Product> items = db.Products.OrderBy(x => x.Title).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult SortByPrice(string Searchtext)
        {
            IEnumerable<Product> items = db.Products.OrderBy(x => x.Price).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult SortByPriceGiam(string Searchtext)
        {
            IEnumerable<Product> items = db.Products.OrderByDescending(x => x.Price).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }
        public ActionResult SortByNameZA(string Searchtext)
        {
            IEnumerable<Product> items = db.Products.OrderByDescending(x => x.Title).ToList();
            if (!string.IsNullOrEmpty(Searchtext))
            {
                char[] charArray = Searchtext.ToCharArray();
                bool foundSpace = true;
                //sử dụng vòng lặp for lặp từng phần tử trong mảng
                for (int i = 0; i < charArray.Length; i++)
                {
                    //sử dụng phương thức IsLetter() để kiểm tra từng phần tử có phải là một chữ cái
                    if (Char.IsLetter(charArray[i]))
                    {
                        if (foundSpace)
                        {
                            //nếu phải thì sử dụng phương thức ToUpper() để in hoa ký tự đầu
                            charArray[i] = Char.ToUpper(charArray[i]);
                            foundSpace = false;
                        }
                    }
                    else
                    {
                        foundSpace = true;
                    }
                }
                //chuyển đổi kiểu mảng char thàng string
                Searchtext = new string(charArray);
                items = items.Where(x => x.Alias.Contains(Searchtext) || x.Title.Contains(Searchtext));
            }
            return View(items);
        }

        public void updateStarRating(int ProductId)
        {
            var reviews = db.Reviews.Where(x => x.ProductId == ProductId);
            float starAverage = (float)Math.Round(reviews.Average(x => x.StarRating) * 2, MidpointRounding.AwayFromZero) / 2;

            // Cập nhật giá trị trung bình đánh giá của sản phẩm
            var product = db.Products.FirstOrDefault(p => p.Id == ProductId);
            if (product != null)
            {
                product.StarRating = starAverage;
                db.SaveChanges();
            }
        }


        public ActionResult Detail(string alias, int id, int page = 1, int pageSize = 3)
        {
            var reviewList = new List<ReviewViewModel>();
            string userId = User.Identity.GetUserId();
            ViewBag.UserId = userId;
            var user = db.Users.FirstOrDefault(u => u.Id == userId);
            if (user != null)
            {
                var name = user.FullName;
                ViewBag.name = name;
                var email = user.Email;
                ViewBag.email = email;
                var image = user.Images;
                ViewBag.image = image;

                Debug.WriteLine("Name: " + name);
                // Perform other operations with the user's name
            }

            var reviews = db.Reviews.Where(_ => _.ProductId == id);

            // Tính số lượng đánh giá và số trang
            int totalReviews = reviews.Count();
            int totalPages = (int)Math.Ceiling((double)totalReviews / pageSize);

            // Lấy danh sách đánh giá cho trang hiện tại
            reviews = reviews.OrderByDescending(r => r.Date);
            var pagedReviews = reviews.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Truyền danh sách đánh giá và thông tin phân trang vào ViewBag hoặc Model
            ViewBag.Reviews = pagedReviews;
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = page;

            var item = db.Products.Find(id);
            if (item != null)
            {
                db.Products.Attach(item);
                item.ViewCount = item.ViewCount + 1;
                db.Entry(item).Property(x => x.ViewCount).IsModified = true;
                db.SaveChanges();
            }

Views/Products/Index.cshtml
@model PagedList.PagedList<CosmeticsStore.Models.EF.Product>
@using PagedList.Mvc
@using PagedList;
@{
    ViewBag.Title = "Danh sách sản phẩm";
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_styles.css">
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/categories_responsive.css">
<style>
</style>
<div class="container product_section_container">
    <div class="row">
        <div class="col product_section clearfix">

            <!-- Breadcrumbs -->

            <div class="breadcrumbs d-flex flex-row align-items-center">
                <ul>
                    <li><a href="san-pham">Sản Phẩm</a></li>
                    <li class="active"><a href="/"><i class="fa fa-angle-right" aria-hidden="true"></i>@ViewBag.CateName</a></li>
                </ul>
            </div>

            <!-- Sidebar -->

            <div class="sidebar">
                <div class="sidebar_section">
                    <div class="sidebar_title">
                        <h5>Danh Mục Sản Phẩm</h5>
                    </div>
                    @Html.Action("MenuLeft", "Menu", new { id = ViewBag.CateId })
                </div>

                <!-- Price Range Filtering -->
                <div class="sidebar_section">
                    <div class="sidebar_title">
                        <h5>Lọc theo Giá</h5>
                    </div>
                    <p>
                        <input type="text" id="amount" readonly style="border:0; font-weight:bold;">
                        <input type="hidden" id="FromAmount" />
                        <input type="hidden" id="ToAmount" />
                    </p>
                    <div id="slider-range"></div>
                    <div class="filter_button"><span>Lọc</span></div>

                    <hr />
                    @Html.Action("Refesh", "Home")
                </div>
            </div>

            <!-- Main Content -->

            <div class="main_content">

                <!-- Products -->

                <div class="products_iso">
                    <div class="row">
                        <div class="col-10">

                            <!-- Product Sorting -->

                            <div class="product_sorting_container product_sorting_container_top">
                                <ul class="product_sorting">
                                    <li>
                                        <span class="type_sorting_text">Sắp xếp</span>
                                        <i class="fa fa-angle-down"></i>
                                        <ul class="sorting_type">
                                            <li><a style="color: #fe4c50" href="~/Products/index">Mặc Định</a></li>
                                            <li><a style="color: #fe4c50" href="~/Products/SortByName">A -> Z</a></li>
                                            <li><a style="color: #fe4c50" href="~/Products/SortByNameZA">Z -> A</a></li>
                                            <li><a style="color: #fe4c50" href="~/Products/SortByPrice">Giá Tăng Dần</a></li>
                                            <li><a style="color: #fe4c50" href="~/Products/SortByPriceGiam">Giá Giảm Dần</a></li>
                                        </ul>
                                    </li>
                                    @*<li>
                                            <span>Show</span>
                                            <span class="num_sorting_text">6</span>
                                            <i class="fa fa-angle-down"></i>
                                            <ul class="sorting_num">
                                                <li class="num_sorting_btn"><span>6</span></li>
                                                <li class="num_sorting_btn"><span>12</span></li>
                                                <li class="num_sorting_btn"><span>24</span></li>
                                            </ul>
                                        </li>*@
                                </ul>

                            </div>

                        </div>
                        <div class="col-2">
                            <form>
                                @using (Html.BeginForm("index", "Products", FormMethod.Post, new { }))
                                {
                                    <div class="search-box">
                                        <input id="Searchtext" name="Searchtext" type="text" placeholder="Tên sản phẩm">
                                        <button type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                    @*<div class="input-group">
                                            <input id="Searchtext" name="Searchtext" type="text" class="form-control" placeholder="Tên sản phẩm">
                                            <div class="input-group-append">
                                                <button type="submit" class="btn btn-lg btn-outline-danger">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </div>
                                        </div>*@
                                }

                            </form>
                        </div>

                    </div>

                    <!-- Product Grid -->

                    <div class="product-grid">

                        <!-- Product 1 -->
                        @if (Model != null && Model.Any())
                        {
                            foreach (var item in Model)
                            {
                                <!-- Product 1 -->
                                var strImge = "";
                                var img = item.ProductImage.FirstOrDefault(x => x.IsDefault);
                                if (img != null)
                                {
                                    strImge = img.Image;
                                }
                                <div class="product-item @item.ProductCategory.Alias">
                                    <div class="product discount product_filter">
                                        <div class="product_image">
                                            <img src="@strImge" alt="@item.Title">
                                        </div>
                                        <div class="favorite favorite_left"></div>
                                        @if (item.PriceScale > 0)
                                        {
                                            <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>sale</span></div>
                                        }
                                        <div class="product_info">
                                            <h6 class="product_name"><a href="/chi-tiet/@item.Alias-p@(item.Id)" data-id="@item.Id">@item.Title</a></h6>
                                            @if (item.PriceScale > 0)
                                            {
                                                <div class="product_price">@CosmeticsStore.Common.Common.FormatNumber(item.PriceScale, 0)đ<span>@CosmeticsStore.Common.Common.FormatNumber(item.Price, 0)đ</span></div>
                                            }
                                            else
                                            {
                                                <div class="product_price">@CosmeticsStore.Common.Common.FormatNumber(item.Price, 0)đ</div>
                                            }
                                        </div>
                                    </div>
                                    @if (item.Quantity <= 0)
                                    {
                                        <div class="red_button add_to_cart_button"><a href="#">Hết Hàng</a></div>
                                    }
                                    else
                                    {
                                        <div class="red_button add_to_cart_button"><a href="#" class="btnAddToCart" data-id="@item.Id">Thêm vào giỏ hàng</a></div>
                                    }

                                </div>
                            }
                        }

                    </div>
                    <div class="row">
                        <div class="col-9"></div>
                        <div class="col-3" style="text-align:right;">
                            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
                        </div>
                    </div>
                    <!-- Product Sorting -->
                    @*<div class="product_sorting_container product_sorting_container_bottom clearfix">
                            <ul class="product_sorting">
                                <li>
                                    <span>Show:</span>
                                    <span class="num_sorting_text">04</span>
                                    <i class="fa fa-angle-down"></i>
                                    <ul class="sorting_num">
                                        <li class="num_sorting_btn"><span>01</span></li>
                                        <li class="num_sorting_btn"><span>02</span></li>
                                        <li class="num_sorting_btn"><span>03</span></li>
                                        <li class="num_sorting_btn"><span>04</span></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>*@

                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Content/assets/js/categories_custom.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>
        function initPriceSlider() {
            $("#slider-range").slider(
                {
                    range: true,
                    min: 0,
                    max: 5000000,
                    values: [0, 500000],
                    slide: function (event, ui) {
                        $("#amount").val("đ" + ui.values[0] + " - đ" + ui.values[1]);
                        $('#FromAmount').val(ui.values[0]);
                        $('#ToAmount').val(ui.values[1]);
                    }
                });

            $("#amount").val("đ" + $("#slider-range").slider("values", 0) + " - đ" + $("#slider-range").slider("values", 1));
        }
    </script>
}

Views/Products/Partial_ItemsByCateId.cshtml
@model IEnumerable<CosmeticsStore.Models.EF.Product>

@if (Model != null && Model.Any())
{
    foreach (var item in Model)
    {
        <!-- Product 1 -->
        var strImge = "";
        var img = item.ProductImage.FirstOrDefault(x => x.IsDefault);
        if (img != null)
        {
            strImge = img.Image;
        }
        <div class="product-item @item.ProductCategory.Alias">
            <div class="product discount product_filter">
                <div class="product_image">
                    <img src="@strImge" alt="@item.Title">
                </div>
                <div class="favorite favorite_left"></div>
                @if (item.PriceScale > 0)
                {
                    <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>sale</span></div>
                }
                <div class="product_info">
                    <h6 class="product_name"><a href="/chi-tiet/@item.Alias-p@(item.Id)">@item.Title</a></h6>
                    @if (item.PriceScale > 0)
                    {
                        <div class="product_price">@CosmeticsStore.Common.Common.FormatNumber(item.PriceScale, 0)đ<span>@CosmeticsStore.Common.Common.FormatNumber(item.Price, 0)đ</span></div>
                    }
                    else
                    {
                        <div class="product_price">@CosmeticsStore.Common.Common.FormatNumber(item.Price, 0)đ</div>
                    }
                </div>
            </div>
            <div class="red_button add_to_cart_button"><a href="#" class="btnAddToCart" data-id="@item.Id">THÊM VÀO GIỎ HÀNG</a></div>
        </div>
    }

}

Views/Products/Partial_ProductSales.cshtml
@model IEnumerable<CosmeticsStore.Models.EF.Product>
@using CosmeticsStore.Common 
@if (Model != null && Model.Any())
{
     <div class="best_sellers">
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <div class="section_title new_arrivals_title">
                            <h2>Sản Phẩm Giảm Giá</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <div class="product_slider_container">
                            <div class="owl-carousel owl-theme product_slider">

                                @foreach (var item in Model)
                                {
                                    var strImge = "";
                                    var img = item.ProductImage.FirstOrDefault(x => x.IsDefault);
                                    if (img != null)
                                    {
                                        strImge = img.Image;
                                    }
                                    <div class="owl-item product_slider_item">
                                        <div class="product-item">
                                            <div class="product discount">
                                                <div class="product_image">
                                                    <img src="@strImge" alt="">
                                                </div>
                                                <div class="favorite favorite_left"></div>
                                                @if (item.PriceScale > 0)
                                                {
                                                    <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>sale</span></div>
                                                }
                                                <div class="product_info">
                                                    <h6 class="product_name"><a href="/chi-tiet/@item.Alias-p@(item.Id)">@item.Title</a></h6>
                                                    @if (item.PriceScale > 0)
                                                    {
                                                        <div class="product_price">@Common.FormatNumber(item.PriceScale, 0)đ<span>@Common.FormatNumber(item.Price, 0)đ</span></div>
                                                    }
                                                    else
                                                    {
                                                        <div class="product_price">@Common.FormatNumber(item.Price, 0)đ</div>
                                                    }
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            <!-- Slider Navigation -->

                            <div class="product_slider_nav_left product_slider_nav d-flex align-items-center justify-content-center flex-column">
                                <i class="fa fa-chevron-left" aria-hidden="true"></i>
                            </div>
                            <div class="product_slider_nav_right product_slider_nav d-flex align-items-center justify-content-center flex-column">
                                <i class="fa fa-chevron-right" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}